import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "@mui/material";
import { Router, useRouter } from "next/router";
import TableFilter from "@/@core/components/table-filter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Home Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          marginTop: "5em",
        }}
      >
        <TableFilter
          title={"Dashboard"}
          buttonText={"Upload"}
          filterBtn={false}
          searchFeild={false}
          isBtn={false}
          handleCreateFunction={(abc: any) => {}}
          handleSearch={(e: any) => {}}
          handleFilter={({ filterValue, filterName }: any) => {}}
          applyFilters={() => {}}
        />
        <Button
          sx={{
            background: "grey",
            color: "white",
            display: "flex",
            alignItems: "center",
            alignContent: "center",
            ml: 2,
          }}
          onClick={() => {
            router.push("/assets");
          }}
        >
          Go to Assets
        </Button>
      </div>
    </>
  );
}
